openapi: 3.0.3
info:
  title: TWISTYtasks
  description: |-
    Welcome to TWISTYtasks your home for everything tasks related. For more information, please visit our home at [https://insertname.here](https://insertname.here).

    You can help us improve our API and Application by submitting feature requests at [https://insertticketsite.here](https://insertticketsite.here).

    For any issues or bugs please help us by providing a ticket here at [https://insertticketsite.here](https://insertticketsite.here)
  contact:
    email: insertemail@here.com
  version: 1.0.0
servers:
- url: https://tasks.domain/api/v1
- url: https://localhost:8000/api/v1
tags:
- name: user
  description: Everything about users
- name: authors
  description: Access to users authors
- name: tasks
  description: Access to users tasks
paths:
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
  /user/createWithList:
    post:
      tags:
      - user
      summary: Creates list of users with given input array
      description: Creates list of users with given input array
      operationId: createUsersWithListInput
  /user/login:
    get:
      tags:
      - user
      summary: Logs user into the system
      description: ""
      operationId: loginUser
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
  /user/{username}:
    get:
      tags:
      - user
      summary: Get user by user name
      description: ""
      operationId: getUserByName
    put:
      tags:
      - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
  /tasks:
    put:
      tags:
      - tasks
      summary: Update an existing tasks
      description: Update an existing tasks by Id
      operationId: updateTasks
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
    post:
      tags:
      - tasks
      summary: Add a new tasks to the store
      description: Add a new tasks to the store
      operationId: addTasks
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
  /tasks/findByStatus:
    get:
      tags:
      - tasks
      summary: Finds Tasks by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findTasksByStatus
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
  /tasks/findByAuthors:
    get:
      tags:
      - tasks
      summary: Finds tasks by authors
      description: Multiple authors can be provided with comma separated strings.
      operationId: findTasksByAuthors
      security:
      - tapps_auth:
        - write:tapps
        - read:tapps
  /tasks/{taskId}:
    get:
      tags:
      - tasks
      summary: Find Tasks by ID
      description: Returns a single Task
      operationId: getTaskById
      security:
      - api_key: []
      - tapps_auth:
        - write:tasks
        - read:tasks
    delete:
      tags:
      - tasks
      summary: Archives a task
      description: Archives a task from the app
      operationId: archiveTask
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
  /authors/{authorId}:
    get:
      tags:
      - authors
      summary: Get an author
      description: Gets a author by id
      operationId: getAuthorById
      security:
      - api_key: []
      - tapps_auth:
        - write:tasks
        - read:tasks
    delete:
      tags:
      - authors
      summary: Archives a task
      description: Archives a task from the app
      operationId: archiveAuthor
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
  /authors/findByTasks:
    get:
      tags:
      - authors
      summary: Finds tasks by authors
      description: Multiple authors can be provided with comma separated strings.
      operationId: findAuthorsByTask
      security:
      - tapps_auth:
        - write:tapps
        - read:tapps
  /authors/findByStatus:
    get:
      tags:
      - authors
      summary: Finds Author by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findAuthorByStatus
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
  /authors:
    put:
      tags:
      - authors
      summary: Update an existing author
      description: Update an existing author by Id
      operationId: updateAuthor
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
    post:
      tags:
      - authors
      summary: Add a new Author to tapps
      description: Add a new author to tapps
      operationId: addAuthor
      security:
      - tapps_auth:
        - write:tasks
        - read:tasks
components:
  securitySchemes:
    tapps_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:tasks: modify pets in your account
            read:tasks: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
