// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlite

import (
	"database/sql"
	"time"
)

type Author struct {
	ID      string
	Name    string
	ClassID string
	BookID  string
}

type AuthorsToTasksRelation struct {
	ID       string
	AuthorID string
	TaskID   string
}

type Book struct {
	ID      string
	Name    string
	ClassID string
}

type Capp struct {
	ID   string
	Name string
}

type Class struct {
	ID       string
	Rating   string
	Caveat   string
	Relative string
}

type Group struct {
	ID   string
	Name string
}

type Mapp struct {
	ID   string
	Name string
}

type Relative struct {
	ID   string
	Name string
}

type Task struct {
	ID      string
	Name    string
	Type    sql.NullString
	Status  sql.NullString
	ClassID sql.NullString
	User    sql.NullString
	Author  sql.NullString
}

type TaskCapp struct {
	TaskID string
	CappID sql.NullString
}

type TaskMapp struct {
	TaskID string
	MappID sql.NullString
}

type TasksType struct {
	ID       string
	TaskType string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	Email     string
	Username  string
	ApiKey    string
}

type UsersGroupsRelation struct {
	Userid  string
	Groupid string
}
