// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package psql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID      uuid.UUID
	Name    string
	ClassID uuid.UUID
}

type Authorstotasksrelation struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
	TaskID   uuid.UUID
}

type Capp struct {
	ID   uuid.UUID
	Name string
}

type Class struct {
	ID       uuid.UUID
	Rating   string
	Caveat   sql.NullString
	Relative []string
}

type Group struct {
	ID   uuid.UUID
	Name string
}

type Mapp struct {
	ID   uuid.UUID
	Name string
}

type Task struct {
	ID      uuid.UUID
	Name    string
	Type    sql.NullString
	Status  sql.NullString
	ClassID sql.NullString
	User    sql.NullString
	Author  sql.NullString
}

type Taskcapp struct {
	TaskID uuid.UUID
	CappID uuid.NullUUID
}

type Taskmapp struct {
	TaskID uuid.UUID
	MappID uuid.NullUUID
}

type Taskstype struct {
	ID       uuid.UUID
	TaskType string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	Email     string
	Username  string
	ApiKey    string
}

type Usersgroupsrelation struct {
	Userid  uuid.UUID
	Groupid uuid.UUID
}
